version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: userhub
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - images_data:/app/images
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userhub
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    restart: on-failure

  nginx1:
    image: openresty/openresty:alpine
    container_name: nginx1
    ports:
      - "8081:80"
    depends_on:
      - app
      - redis
    volumes:
      - ./nginx/config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/lua:/etc/nginx/lua
      - ./nginx/cache:/var/cache/nginx
      - images_data:/app/images

  nginx2:
    image: openresty/openresty:alpine
    container_name: nginx2
    ports:
      - "8082:80"
    depends_on:
      - app
      - redis
    volumes:
      - ./nginx/config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/lua:/etc/nginx/lua
      - ./nginx/cache:/var/cache/nginx
      - images_data:/app/images

  nginx3:
    image: openresty/openresty:alpine
    container_name: nginx3
    ports:
      - "8083:80"
    depends_on:
      - app
      - redis
    volumes:
      - ./nginx/config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/lua:/etc/nginx/lua
      - ./nginx/cache:/var/cache/nginx
      - images_data:/app/images

volumes:
  postgres_data:
  images_data:
