spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userhub
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: DEBUG