spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userhub
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  data:
    redis:
      host: redis
      port: 6379

  session:
    store-type: redis
    timeout: 10m

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  upload:
    dir: /app/images/avatars